In [1]:
import numpy as np

In [25]:
a = np.arange(0, 25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
b = np.array([[0,3,0],
              [3,5,3],
              [0,3,0]],
           )
b

array([[0, 3, 0],
       [3, 5, 3],
       [0, 3, 0]])

In [24]:
b = np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
b = np.array([[[0,3,0],
              [3,5,3],
              [0,3,0]],
            [[0,3,0],
              [3,5,3],
              [0,3,0]]
            ,[[0,3,0],
              [3,5,3],
              [0,3,0]]])
b

array([[[0, 3, 0],
        [3, 5, 3],
        [0, 3, 0]],

       [[0, 3, 0],
        [3, 5, 3],
        [0, 3, 0]],

       [[0, 3, 0],
        [3, 5, 3],
        [0, 3, 0]]])

In [11]:
a[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [12]:
a[0:3,0:3]*b      # r = np.mean(a[i:i+3,j:j+3]*b)
a[i,j] = (r,r,r)

array([[ 0,  3,  0],
       [15, 30, 21],
       [ 0, 33,  0]])

In [13]:
np.mean(a[0:3,0:3]*b)

11.333333333333334

In [14]:
np.mean(a[0:3,0:3]*b, axis=(0,1))

array([ 1., 22., 11.])

In [16]:
a = np.arange(0, 75).reshape(3,5,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [18]:
a[:, 0:3,0:3]

array([[[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12]],

       [[25, 26, 27],
        [30, 31, 32],
        [35, 36, 37]],

       [[50, 51, 52],
        [55, 56, 57],
        [60, 61, 62]]])

In [19]:
a[:, 0:3,0:3] * b

array([[[  0,   3,   0],
        [ 15,  30,  21],
        [  0,  33,   0]],

       [[  0,  78,   0],
        [ 90, 155,  96],
        [  0, 108,   0]],

       [[  0, 153,   0],
        [165, 280, 171],
        [  0, 183,   0]]])

In [21]:
np.mean(a[:, 0:3,0:3] * b, axis=(1,2))

array([ 11.33333333,  58.55555556, 105.77777778])

In [22]:
!ls

"ls" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


In [ ]:
!pip install pillow

In [26]:
a = np.array([1,2,0,-1,-5])

In [27]:
a[a < 0] = 0

In [28]:
a

array([1, 2, 0, 0, 0])

In [45]:
b = np.array([[[-1,-1,-1],
              [-1,9, -1],
              [-1, -1, -1]],
            [[-1,-1,-1],
              [-1,9, -1],
              [-1, -1, -1]],
            [[-1,-1,-1],
              [-1,9, -1],
              [-1, -1, -1]]])


In [46]:
np.swapaxes(b,2,0)[:,:,0]

array([[-1, -1, -1],
       [-1,  9, -1],
       [-1, -1, -1]])

array([[-1, -1, -1],
       [-1,  9, -1],
       [-1,  9, -1]])