1)
main.py
В случайных местах но на расстоянии не меньше 6 находятся на поле 800 на 800 К касс
N=100 шушучиков появляются в случайных местах но не на касах
Шушунчики случайно двигаются. С вероятностью 80% они сохраняют свое направление с вероятностью 20% они выбирают другое направление. Если на расстоянии 3 от шушунчика находится касса он устремлсяется в нее. Если шушунчику мешает идти другой шушунчик то шушунчик либо меняет направление движения (если он не в зоне действия кассы) или если рядом касса то шушунчик просто стоит и ждет пока возможность прохода освободится то есть он не может удалиться от кассы а только приблизиться. Притом можно приближаться обходя других шушунчиков если каждый шаг приближает или не отдаляет от кассы.
Если шушунчик попадает на кассу он генерирует случайно число от 1 до 9 и столько времени стоит на кассе - обслуживается. В это время другие шушунчики стоят в очереди и не могут попасть на кассу.
После того как у шушунчика кончилось время обслуживания он пропадает с кассы и где-то на поле появляется новый шушунчик

Каждый запуск должен состоять из 480 минут - итераций.

На каждом запуске оценивает сколько было плохих минут из этих 480.
Плохая минут это когда какой-либо шушунчик хотя бы на одной из касс ждет в очереди уже больше 15 минут(циклов). В очереди считаются все шушунчики которые находятся на расстоянии 3 от кассы.

В итоге вы получаете количество плохих минут и вычисляете долю плохих минут деля их на 480
Долю плохих минут округляете до 0.05
то есть вы получаете числа 0, 0.05, 0.1, 0.15, 0.2, 0.25  итд 0.9, 0.95, 1


Вы запускаете моделирование 100 раз и считаете сколько раз получилось каждое из значений доли плохих минут

Например
0 появился 0 раз
0.05 появился 1 раз
0.1 появился 1 раз
0.15 появился  2 раза
итд

Строите и сохраняете график как stat_bad_min.png 
по оси икс это доля плохих минут по игрек это количество какой раз за 100 моделирование случалась такая доля.

Так же аналогично доле плохих минут постройте графики
среднего времени обслуживания stat_time_work.png
среднего времени ожидания stat_time_wait.png
среднего количества появления новых клиентов у касс за минуту stat_new_clicent.png


Подберите минимальный параметр К такой,  чтобы при 100 моделированиях не более чем в 95 из них доля плохого времени была больше 0.1

задание до 18.03.2023

In [2]:
a = [1,2,3]
b = [2,1,5]
c = list([a[i] - b[i] for i in range(len(a))])
c

[-1, 1, -2]

In [9]:
import numpy as np
a = np.round(np.random.random((3,3)))

In [14]:
a==1

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False,  True]])

In [19]:
x = np.indices((3,3))
x

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [24]:
list(zip(x[0][a==1],x[1][a==1]))

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 2)]

In [25]:
(5,3) in [(2,1), (5,3)]

True

In [26]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [27]:
np.array([[1,2],[3,4]]) - np.array([0.5, 0.1])

array([[0.5, 1.9],
       [2.5, 3.9]])