In [1]:
import numpy as np

In [23]:
t = np.arange(1, 10, 0.1)
t

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [24]:
def y_true(t, y0, v0, a):
    return y0 + v0*t + (a*t**2)/2

In [25]:
y = y_true(t, 0, 0, 9.8)
y

array([  4.9  ,   5.929,   7.056,   8.281,   9.604,  11.025,  12.544,
        14.161,  15.876,  17.689,  19.6  ,  21.609,  23.716,  25.921,
        28.224,  30.625,  33.124,  35.721,  38.416,  41.209,  44.1  ,
        47.089,  50.176,  53.361,  56.644,  60.025,  63.504,  67.081,
        70.756,  74.529,  78.4  ,  82.369,  86.436,  90.601,  94.864,
        99.225, 103.684, 108.241, 112.896, 117.649, 122.5  , 127.449,
       132.496, 137.641, 142.884, 148.225, 153.664, 159.201, 164.836,
       170.569, 176.4  , 182.329, 188.356, 194.481, 200.704, 207.025,
       213.444, 219.961, 226.576, 233.289, 240.1  , 247.009, 254.016,
       261.121, 268.324, 275.625, 283.024, 290.521, 298.116, 305.809,
       313.6  , 321.489, 329.476, 337.561, 345.744, 354.025, 362.404,
       370.881, 379.456, 388.129, 396.9  , 405.769, 414.736, 423.801,
       432.964, 442.225, 451.584, 461.041, 470.596, 480.249])

In [26]:
y <= 10

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [27]:
y[y <= 10]

array([4.9  , 5.929, 7.056, 8.281, 9.604])

In [28]:
t[y <= 10]

array([1. , 1.1, 1.2, 1.3, 1.4])